[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test"
cache = true
cache_path = "cache_forge"
force = false
evm_version = "paris"
gas_reports = ["*"]

[rpc_endpoints]
sepolia = "${RPC_URL_SEPOLIA}"
amoy = "${RPC_URL_AMOY}"

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }
